GET http://localhost:3001/patients



###

POST http://localhost:3001/patients
Content-Type: application/json

{
    "email": "test1@gmail.com"
}

###

DELETE http://localhost:3001/patients/614804a90b46066e2f91de43